name: "PR Branch Labeler"
description: "Automatically label your PRs based on their branches."
author: "Florian Fittschen"
inputs:
  repo-token:
    description: "Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
runs:
  using: "node12"
  main: "lib/main.js"
branding:
  icon: "tag"
  color: "orange"
